# Generated by Django 4.2.30 on 2026-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
